# Generated by Django 4.1.6 on 2023-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fantasy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='fiction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='horror',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='non_fiction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='science_fiction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='thriller',
            field=models.BooleanField(default=False),
        ),
    ]
